# ./create-stack.sh capstone-cluster cluster.yml
# ./delete-stack.sh capstone-cluster
---
Description: >
  Amazon EKS Cluster with assigned managed Cluster Role
  Part of Capstone project for Cloud DevOps Engineering Nanodegree

Parameters:
    EnviromentName:
        Description: The default prefix for cluster components
        Type: String
        Default: Capstone
 
Resources:
    ClusterRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - eks.amazonaws.com
              Action:
              - sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

    Cluster:
        Type: AWS::EKS::Cluster
        DependsOn: ClusterRole
        Properties:
            Name: !Sub ${EnviromentName}-Cluster
            Version: 1.17
            RoleArn: !GetAtt ClusterRole.Arn
            ResourcesVpcConfig:
                SecurityGroupIds:
                    Fn::Split:
                        - ","
                        - Fn::ImportValue:
                            Fn::Sub:
                                ${EnviromentName}-ClusterControlPlaneSecurityGroup
                SubnetIds:
                    Fn::Split:
                        - ","
                        - Fn::ImportValue:
                            Fn::Sub:
                                ${EnviromentName}-SubnetIds

Outputs:
  ClusterName:
    Description: Name of created cluster
    Value: !Ref Cluster
    Export:
      Name: !Sub ${EnviromentName}-ClusterName
    
  ClusterRoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt ClusterRole.Arn
    Export:
      Name: !Sub ${EnviromentName}-ClusterRoleArn

# usefull following commands  
# aws eks get-token --cluster-name eks-cluster-capstone
# aws eks list-clusters
# aws eks describe-cluster --name eks-cluster-capstone
# aws ec2 describe-security-groups --group-ids <sg-0b....>
# aws eks --region eu-west-2 update-kubeconfig --name eks-cluster-capstone
# aws iam list-users
# aws sts get-caller-identity