# ./create-stack.sh capstone-cluster cluster.yml
# ./delete-stack.sh capstone-cluster
---
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EKS Cluster

Parameters:
    ClusterName:
        Description: The default name for cluster control plane
        Type: String
        Default: "eks-cluster-capstone"
        
    InfraStackName:
        Description: The default name for cluster network stack definition (VPC, Subnets, SecurityGroups)
        Type: String
        Default: "eks-infra-capstone"
 
Resources:
    EksClusterRole:
        Type: 'AWS::IAM::Role'
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - eks.amazonaws.com
              Action:
              - sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

    CreatedCluster:
        Type: 'AWS::EKS::Cluster'
        DependsOn: EksClusterRole
        Properties:
            Name: !Ref ClusterName
            Version: '1.17'
            RoleArn: !GetAtt EksClusterRole.Arn
            ResourcesVpcConfig:
                SecurityGroupIds:
                    Fn::Split:
                        - ","
                        - Fn::ImportValue:
                            Fn::Sub:
                                "${InfraStackName}-SecurityGroup"
                SubnetIds:
                    Fn::Split:
                        - ","
                        - Fn::ImportValue:
                            Fn::Sub:
                                "${InfraStackName}-SubnetIds"

Outputs:
  CreatedClusterName:
    Description: Name of created cluster
    Value: !Ref CreatedCluster
    
  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt EksClusterRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"
    
# usefull following commands  
# aws eks get-token --cluster-name eks-cluster-capstone
# aws eks list-clusters
# aws eks describe-cluster --name eks-cluster-capstone
# aws ec2 describe-security-groups --group-ids <sg-0b....>
# aws eks --region eu-west-2 update-kubeconfig --name eks-cluster-capstone
# aws iam list-users
# aws sts get-caller-identity