apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-app-deploy
  labels:
    app: jokes-app
  annotations:
spec:
  selector:
    matchLabels:
      app: jokes-app
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:          # terminate and spinup new one one by one
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: jokes-app
    spec:
      containers:
      - name: jokes-app
        image: hubertos/jokes-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /status
            port: 8080
          failureThreshold: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "50m"