  
apiVersion: v1
kind: Service
metadata:
  name: jokes-app-service
  labels:
    app: jokes-app
spec:
  type: LoadBalancer
  selector:
    app: jokes-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080